# Generated by Django 5.1.3 on 2024-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('activity_level', models.IntegerField()),
                ('allergy', models.CharField(max_length=50)),
                ('dietary_preferences', models.CharField(max_length=50)),
                ('health_issues', models.CharField(max_length=50)),
            ],
        ),
    ]
